# generated by datamodel-codegen:
#   filename:  <dict>
#   timestamp: 2026-08-22T07:27:44+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)


class Metric(StrEnum):
    cpu_percent = "cpu_percent"
    memory_percent = "memory_percent"


class Severity(StrEnum):
    warning = "warning"
    critical = "critical"


class AlertEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[
        str,
        Field(examples=["cpu_percent is critically high at 82.3% (threshold: 80%)"]),
    ]
    """
    Human-readable alert description

    Example: 'cpu_percent is critically high at 82.3% (threshold: 80%)'
    """
    metric: Annotated[Metric, Field(examples=["cpu_percent"])]
    """
    Name of the metric that triggered the alert

    Example: 'cpu_percent'
    """
    severity: Annotated[Severity, Field(examples=["critical"])]
    """
    Alert severity level

    Example: 'critical'
    """
    threshold: Annotated[float, Field(examples=[80], ge=0.0)]
    """
    Threshold that was exceeded

    Example: 80
    """
    timestamp: AwareDatetime
    """Time the alert was raised"""
    value: Annotated[float, Field(examples=[82.3], ge=0.0)]
    """
    Current value of the metric

    Example: 82.3
    """


class Scheme(StrEnum):
    basic = "basic"
    bearer = "bearer"
    api_key_header = "api-key-header"
    api_key_query = "api-key-query"


class AuthResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            examples=["https://api.rest.sh/schemas/AuthResponseBody.json"],
        ),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/AuthResponseBody.json'
    """
    authenticated: Annotated[bool, Field(examples=[True])]
    """
    Whether the mock authentication check succeeded

    Example: True
    """
    scheme: Annotated[Scheme, Field(examples=["bearer"])]
    """
    Authentication scheme that accepted the request

    Example: 'bearer'
    """
    subject: Annotated[str | None, Field(examples=["docs-token"])] = None
    """
    Authenticated username, token, or API key

    Example: 'docs-token'
    """


class BookSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    modified: AwareDatetime
    """Last modification time used for conditional requests"""
    url: Annotated[str, Field(examples=["/books/left-hand-of-darkness"])]
    """
    Relative URL for the book resource

    Example: '/books/left-hand-of-darkness'
    """
    version: Annotated[str, Field(examples=["F5D3XF8rF2F="])]
    """
    Opaque version token for conditional requests

    Example: 'F5D3XF8rF2F='
    """


class CachedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/CachedModel.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/CachedModel.json'
    """
    generated: AwareDatetime
    """Time when this response was generated"""
    until: AwareDatetime
    """When the cache will be invalidated"""


class Type(StrEnum):
    login = "login"
    update = "update"
    logout = "logout"


class DocsUser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(examples=["u_123"], min_length=1)]
    """
    User ID

    Example: 'u_123'
    """
    name: Annotated[str, Field(examples=["Alice"], min_length=1)]
    """
    Display name

    Example: 'Alice'
    """


class Method(StrEnum):
    get = "GET"
    post = "POST"
    put = "PUT"
    patch = "PATCH"
    delete = "DELETE"
    head = "HEAD"
    options = "OPTIONS"


class EchoModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/EchoModel.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/EchoModel.json'
    """
    body: Any | None = None
    """Raw request body, either a UTF-8 string or bytes"""
    headers: dict[str, str]
    """HTTP headers"""
    host: Annotated[str | None, Field(examples=["api.rest.sh"])] = None
    """
    Hostname and optional port

    Example: 'api.rest.sh'
    """
    method: Annotated[Method, Field(examples=["GET"])]
    """
    HTTP method used

    Example: 'GET'
    """
    parsed: Any | None = None
    """Parsed request body"""
    path: Annotated[str, Field(examples=["/get"])]
    """
    URL path

    Example: '/get'
    """
    query: dict[str, str] | None = None
    """URL query parameters"""
    url: Annotated[AnyUrl, Field(examples=["https://api.rest.sh/get?show_env=1"])]
    """
    Full URL

    Example: 'https://api.rest.sh/get?show_env=1'
    """


class StudyType(StrEnum):
    high_school = "High School"
    bachelor = "Bachelor"
    master = "Master"
    doctorate = "Doctorate"
    certificate = "Certificate"


class Education(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: Annotated[str | None, Field(examples=["Computer Science"])] = None
    """
    Field of study

    Example: 'Computer Science'
    """
    courses: Annotated[list[str] | None, Field(max_length=20)] = None
    """Relevant courses"""
    end_date: Annotated[AwareDatetime | None, Field(alias="endDate")] = None
    """Education end date"""
    gpa: Annotated[str | None, Field(examples=["3.8"])] = None
    """
    Grade point average or equivalent

    Example: '3.8'
    """
    institution: Annotated[str | None, Field(examples=["University of Example"])] = None
    """
    School or institution name

    Example: 'University of Example'
    """
    start_date: Annotated[AwareDatetime | None, Field(alias="startDate")] = None
    """Education start date"""
    study_type: Annotated[StudyType | None, Field(alias="studyType", examples=["Bachelor"])] = None
    """
    Type of study or credential

    Example: 'Bachelor'
    """


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: str | None = None
    """Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"""
    message: str | None = None
    """Error message text"""
    value: Any | None = None
    """The value at the given location"""


class ErrorModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/ErrorModel.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/ErrorModel.json'
    """
    detail: Annotated[str | None, Field(examples=["Property foo is required but is missing."])] = None
    """
    A human-readable explanation specific to this occurrence of the problem.

    Example: 'Property foo is required but is missing.'
    """
    errors: list[ErrorDetail] | None = None
    """Optional list of individual error details"""
    instance: Annotated[AnyUrl | None, Field(examples=["https://example.com/error-log/abc123"])] = None
    """
    A URI reference that identifies the specific occurrence of the problem.

    Example: 'https://example.com/error-log/abc123'
    """
    status: Annotated[int | None, Field(examples=[400])] = None
    """
    HTTP status code

    Example: 400
    """
    title: Annotated[str | None, Field(examples=["Bad Request"])] = None
    """
    A short, human-readable summary of the problem type. This value should not change between occurrences of the error.

    Example: 'Bad Request'
    """
    type: Annotated[AnyUrl | None, Field(examples=["https://example.com/errors/example"])] = "about:blank"
    """
    A URI reference to human-readable documentation for the error.

    Example: 'https://example.com/errors/example'
    """


class Format(StrEnum):
    jpeg = "jpeg"
    webp = "webp"
    gif = "gif"
    png = "png"
    heic = "heic"


class ImageItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: Annotated[Format, Field(examples=["jpeg"])]
    """
    Image format returned by the fixture

    Example: 'jpeg'
    """
    name: Annotated[str, Field(examples=["Dragonfly"])]
    """
    Human-readable image fixture name

    Example: 'Dragonfly'
    """
    self: Annotated[str, Field(examples=["/image/jpeg"])]
    """
    Relative URL for this image fixture

    Example: '/image/jpeg'
    """


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/Item.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/Item.json'
    """
    enabled: Annotated[bool, Field(examples=[True])]
    """
    Whether the item is enabled

    Example: True
    """
    id: Annotated[str, Field(examples=["alpha"], max_length=64)]
    """
    Stable item identifier; omit or leave empty when creating an item to have one generated

    Example: 'alpha'
    """
    name: Annotated[str, Field(examples=["Alpha item"], max_length=120, min_length=1)]
    """
    Display name

    Example: 'Alpha item'
    """
    tags: Annotated[list[str] | None, Field(examples=[["docs", "example"]], max_length=10)] = None
    """
    Free-form item tags

    Example: ['docs', 'example']
    """
    updated: AwareDatetime
    """Time when the item was last updated"""


class Op(StrEnum):
    add = "add"
    remove = "remove"
    replace = "replace"
    move = "move"
    copy = "copy"
    test = "test"


class JsonPatchOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: Annotated[str | None, Field(alias="from")] = None
    """JSON Pointer for the source of a move or copy"""
    op: Op
    """Operation name"""
    path: str
    """JSON Pointer to the field being operated on, or the destination of a move/copy operation"""
    value: Any | None = None
    """The value to set"""


class Fluency(StrEnum):
    elementary = "Elementary"
    limited_working = "Limited working"
    professional_working = "Professional working"
    full_professional = "Full professional"
    native_or_bilingual = "Native or bilingual"


class Language(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fluency: Annotated[Fluency | None, Field(examples=["Native or bilingual"])] = None
    """
    Language fluency

    Example: 'Native or bilingual'
    """
    language: Annotated[str | None, Field(examples=["English"])] = None
    """
    Language name

    Example: 'English'
    """


class Location(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address: str | None = None
    """
    To add multiple address lines, use 
    . For example, 1234 Glücklichkeit Straße
    Hinterhaus 5. Etage li.
    """
    city: Annotated[str | None, Field(examples=["San Francisco"])] = None
    """
    City or locality

    Example: 'San Francisco'
    """
    country_code: Annotated[
        str | None,
        Field(alias="countryCode", examples=["US"], max_length=2, min_length=2),
    ] = None
    """
    Code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN

    Example: 'US'
    """
    postal_code: Annotated[str | None, Field(alias="postalCode", examples=["94105"])] = None
    """
    Postal or ZIP code

    Example: '94105'
    """
    region: str | None = None
    """The general region where you live. Can be a US state, or a province, for instance."""


class Region(StrEnum):
    us_east_1 = "us-east-1"
    us_west_2 = "us-west-2"
    eu_west_1 = "eu-west-1"
    ap_southeast_1 = "ap-southeast-1"


class MetricEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    active_connections: Annotated[int, Field(examples=[96], ge=0)]
    """
    Number of active HTTP connections

    Example: 96
    """
    cpu_percent: Annotated[float, Field(examples=[62.4], ge=0.0, le=100.0)]
    """
    CPU utilization percentage

    Example: 62.4
    """
    memory_percent: Annotated[float, Field(examples=[71.2], ge=0.0, le=100.0)]
    """
    Memory utilization percentage

    Example: 71.2
    """
    region: Annotated[Region, Field(examples=["us-west-2"])]
    """
    Data center region reporting metrics

    Example: 'us-west-2'
    """
    requests_per_second: Annotated[float, Field(examples=[421.5], ge=0.0, le=2000.0)]
    """
    Inbound request rate

    Example: 421.5
    """
    timestamp: AwareDatetime
    """Time the metrics were sampled"""


class Profile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    network: Annotated[str | None, Field(examples=["Twitter"], min_length=1)] = None
    """
    Profile network or service name

    Example: 'Twitter'
    """
    url: Annotated[AnyUrl | None, Field(examples=["http://twitter.example.com/neutralthoughts"])] = None
    """Example: 'http://twitter.example.com/neutralthoughts'"""
    username: Annotated[str | None, Field(examples=["neutralthoughts"], min_length=1)] = None
    """
    Username on the profile network

    Example: 'neutralthoughts'
    """


class Rating(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: AwareDatetime
    """Time when the rating was recorded"""
    rating: Annotated[float, Field(examples=[4.6], ge=0.0, le=5.0, multiple_of=0.1)]
    """
    Rating value on a 0 to 5 scale

    Example: 4.6
    """


class Level(StrEnum):
    beginner = "Beginner"
    intermediate = "Intermediate"
    advanced = "Advanced"
    expert = "Expert"


class Skill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    keywords: Annotated[list[str] | None, Field(max_length=20, min_length=1)] = None
    """Specific technologies or practices"""
    level: Annotated[Level | None, Field(examples=["Advanced"])] = None
    """
    Proficiency level

    Example: 'Advanced'
    """
    name: Annotated[str | None, Field(examples=["Web Development"])] = None
    """
    Skill category name

    Example: 'Web Development'
    """


class SubObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binary: Annotated[str, Field(json_schema_extra={"contentEncoding": "base64"}, min_length=1)]
    """Small binary payload encoded as base64 in JSON"""
    binary_long: Annotated[str, Field(json_schema_extra={"contentEncoding": "base64"}, min_length=1)]
    """Longer binary payload encoded as base64 in JSON"""
    date: AwareDatetime
    """Calendar date represented as an RFC 3339 timestamp"""
    date_time: AwareDatetime
    """Full timestamp with timezone"""
    url: Annotated[AnyUrl, Field(examples=["https://rest.sh/"])]
    """
    Absolute URL example

    Example: 'https://rest.sh/'
    """


class TokenType(StrEnum):
    bearer = "Bearer"


class TokenResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            examples=["https://api.rest.sh/schemas/TokenResponseBody.json"],
        ),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/TokenResponseBody.json'
    """
    token: Annotated[str, Field(examples=["docs-token-alice"])]
    """
    Mock bearer token for documentation examples

    Example: 'docs-token-alice'
    """
    token_type: Annotated[TokenType, Field(examples=["Bearer"])]
    """
    Token type

    Example: 'Bearer'
    """
    user: Annotated[str, Field(examples=["alice"])]
    """
    Username from the submitted form

    Example: 'alice'
    """


class TypesModelNullableStruct(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class UploadFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content_type: Annotated[str | None, Field(examples=["image/png"])] = None
    """
    Detected file content type

    Example: 'image/png'
    """
    field: Annotated[str, Field(examples=["avatar"])]
    """
    Multipart field name

    Example: 'avatar'
    """
    filename: Annotated[str, Field(examples=["avatar.png"])]
    """
    Uploaded filename

    Example: 'avatar.png'
    """
    size: Annotated[int, Field(examples=[2048], ge=0)]
    """
    File size in bytes

    Example: 2048
    """


class UploadResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            examples=["https://api.rest.sh/schemas/UploadResponseBody.json"],
        ),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/UploadResponseBody.json'
    """
    fields: dict[str, list[str] | None]
    """Non-file multipart fields grouped by field name"""
    files: list[UploadFile] | None
    """Uploaded file metadata"""


class Volunteer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end_date: Annotated[AwareDatetime | None, Field(alias="endDate")] = None
    """Volunteer role end date"""
    highlights: Annotated[list[str] | None, Field(max_length=10)] = None
    """Notable volunteer accomplishments"""
    organization: Annotated[str | None, Field(examples=["Code for America"])] = None
    """
    Volunteer organization name

    Example: 'Code for America'
    """
    position: Annotated[str | None, Field(examples=["Mentor"])] = None
    """
    Volunteer role

    Example: 'Mentor'
    """
    start_date: Annotated[AwareDatetime | None, Field(alias="startDate")] = None
    """Volunteer role start date"""
    summary: str | None = None
    """Overview of the volunteer work"""
    url: Annotated[AnyUrl | None, Field(examples=["https://www.codeforamerica.org"])] = None
    """Example: 'https://www.codeforamerica.org'"""


class Work(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Annotated[str | None, Field(examples=["Social Media Company"])] = None
    """Example: 'Social Media Company'"""
    end_date: Annotated[AwareDatetime | None, Field(alias="endDate")] = None
    """Role end date, omitted for current roles"""
    highlights: Annotated[list[str] | None, Field(max_length=10)] = None
    """Specify multiple accomplishments"""
    location: Annotated[str | None, Field(examples=["Menlo Park, CA"])] = None
    """Example: 'Menlo Park, CA'"""
    name: Annotated[str, Field(examples=["Facebook"], min_length=1)]
    """
    Employer or organization name

    Example: 'Facebook'
    """
    position: Annotated[str, Field(examples=["Software Engineer"], min_length=1)]
    """
    Job title or role

    Example: 'Software Engineer'
    """
    start_date: Annotated[AwareDatetime | None, Field(alias="startDate")] = None
    """Role start date"""
    summary: str | None = None
    """Give an overview of your responsibilities at the company"""
    url: Annotated[AnyUrl | None, Field(examples=["https://facebook.com"])] = None
    """Example: 'https://facebook.com'"""


class GetBase64DecodeResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class GetBase64EncodeResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class ListBooksResponse(RootModel[list[BookSummary] | None]):
    root: list[BookSummary] | None


class PatchBookRequest(RootModel[list[JsonPatchOp] | None]):
    root: list[JsonPatchOp] | None


class PatchBookRequest1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/Book.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/Book.json'
    """
    author: Annotated[str | None, Field(examples=["Ursula K. Le Guin"], max_length=120, min_length=1)] = None
    """
    Primary author

    Example: 'Ursula K. Le Guin'
    """
    published: AwareDatetime | None = None
    """Publication date"""
    rating_average: Annotated[float | None, Field(examples=[4.4], ge=0.0, le=5.0, multiple_of=0.1)] = None
    """
    Average rating on a 0 to 5 scale

    Example: 4.4
    """
    ratings: Annotated[int | None, Field(examples=[1287], ge=0)] = None
    """
    Total number of ratings

    Example: 1287
    """
    recent_ratings: Annotated[list[Any] | None, Field(max_length=10)] = None
    """Most recent rating samples"""
    title: Annotated[
        str | None,
        Field(examples=["The Left Hand of Darkness"], max_length=200, min_length=1),
    ] = None
    """
    Book title

    Example: 'The Left Hand of Darkness'
    """


class GetCookiesResponse(RootModel[dict[str, dict[str, str]]]):
    root: dict[str, dict[str, str]]


class GetCookiesDeleteResponse(RootModel[dict[str, list[str] | None]]):
    root: dict[str, list[str] | None]


class GetCookiesSetResponse(RootModel[dict[str, dict[str, str]]]):
    root: dict[str, dict[str, str]]


class GetFlakyResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetHeadersResponse(RootModel[dict[str, dict[str, str]]]):
    root: dict[str, dict[str, str]]


class ListImagesResponse(RootModel[list[ImageItem] | None]):
    root: list[ImageItem] | None


class GetIpResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class ListItemsResponse(RootModel[list[Item] | None]):
    root: list[Item] | None


class PatchItemRequest(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetProblemResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetResponseHeadersResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class GetSlowResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetSseMetricsResponse1(BaseModel):
    data: AlertEvent
    event: Literal["alert"]
    """The event name."""
    id: int | None = None
    """The event ID."""
    retry: int | None = None
    """The retry time in milliseconds."""


class GetSseMetricsResponse2(BaseModel):
    data: MetricEvent
    event: Literal["metrics"]
    """The event name."""
    id: int | None = None
    """The event ID."""
    retry: int | None = None
    """The retry time in milliseconds."""


class GetSseMetricsResponse(RootModel[list[GetSseMetricsResponse1 | GetSseMetricsResponse2]]):
    root: Annotated[
        list[GetSseMetricsResponse1 | GetSseMetricsResponse2],
        Field(title="Server Sent Events"),
    ]
    """Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification."""


class GetUserAgentResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class GetUuidResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class Basics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[EmailStr | None, Field(examples=["thomas@gmail.com"])] = None
    """
    Contact email address

    Example: 'thomas@gmail.com'
    """
    image: Annotated[AnyUrl | None, Field(examples=["https://example.com/avatar.jpg"])] = None
    """
    URL (as per RFC 3986) to an image in JPEG or PNG format

    Example: 'https://example.com/avatar.jpg'
    """
    label: Annotated[str | None, Field(examples=["Web Developer"], min_length=1)] = None
    """
    Short professional headline

    Example: 'Web Developer'
    """
    location: Location | None = None
    """Primary location"""
    name: Annotated[str, Field(examples=["Thomas Davis"], min_length=1)]
    """
    Full display name

    Example: 'Thomas Davis'
    """
    phone: str | None = None
    """Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923"""
    profiles: Annotated[list[Profile] | None, Field(max_length=10)] = None
    """Online social or professional profiles"""
    summary: str | None = None
    """Write a short 2-3 sentence biography about yourself"""
    updated: AwareDatetime
    """Time when the resume data was last updated"""
    url: AnyUrl | None = None
    """URL (as per RFC 3986) to your website, e.g. personal homepage"""
    verified: Annotated[bool, Field(examples=[True])]
    """
    Whether this example profile has been verified

    Example: True
    """


class Book(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/Book.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/Book.json'
    """
    author: Annotated[str | None, Field(examples=["Ursula K. Le Guin"], max_length=120, min_length=1)] = None
    """
    Primary author

    Example: 'Ursula K. Le Guin'
    """
    published: AwareDatetime | None = None
    """Publication date"""
    rating_average: Annotated[float | None, Field(examples=[4.4], ge=0.0, le=5.0, multiple_of=0.1)] = None
    """
    Average rating on a 0 to 5 scale

    Example: 4.4
    """
    ratings: Annotated[int | None, Field(examples=[1287], ge=0)] = None
    """
    Total number of ratings

    Example: 1287
    """
    recent_ratings: Annotated[list[Rating] | None, Field(max_length=10)] = None
    """Most recent rating samples"""
    title: Annotated[str, Field(examples=["The Left Hand of Darkness"], max_length=200, min_length=1)]
    """
    Book title

    Example: 'The Left Hand of Darkness'
    """


class DocsEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[str, Field(examples=["login event for Alice"])]
    """
    Human-readable message

    Example: 'login event for Alice'
    """
    timestamp: AwareDatetime
    """Event timestamp"""
    type: Annotated[Type, Field(examples=["login"])]
    """
    Event type

    Example: 'login'
    """
    user: DocsUser
    """User associated with the event"""


class Resume(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/Resume.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/Resume.json'
    """
    basics: Basics
    """Core profile and contact information"""
    education: list[Education] | None = None
    """Education history"""
    languages: list[Language] | None = None
    """Spoken languages"""
    skills: list[Skill] | None = None
    """Skills and keywords"""
    volunteer: list[Volunteer] | None = None
    """Volunteer experience"""
    work: Annotated[list[Work] | None, Field(min_length=1)]
    """Professional work history"""


class TypesModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(alias="$schema", examples=["https://api.rest.sh/schemas/TypesModel.json"]),
    ] = None
    """
    A URL to the JSON Schema for this object.

    Example: 'https://api.rest.sh/schemas/TypesModel.json'
    """
    boolean: Annotated[bool, Field(examples=[True])]
    """
    Boolean example value

    Example: True
    """
    integer: Annotated[int, Field(examples=[42], ge=0, le=100)]
    """
    Integer example with validation bounds

    Example: 42
    """
    nullable: TypesModelNullableStruct
    """Nullable object field; this response intentionally returns null"""
    number: Annotated[float, Field(examples=[123.45], ge=0.0, le=1000.0, multiple_of=0.01)]
    """
    Floating point example with precision constraints

    Example: 123.45
    """
    object: SubObject
    """Nested object showing binary, date-time, and URI fields"""
    string: Annotated[str, Field(examples=["Hello, world!"], max_length=120, min_length=1)]
    """
    Plain UTF-8 string example

    Example: 'Hello, world!'
    """
    tags: Annotated[
        list[str] | None,
        Field(examples=[["example", "short"]], max_length=5, min_length=1),
    ]
    """
    Short list of descriptive tags

    Example: ['example', 'short']
    """


class GetEventsResponse1(BaseModel):
    data: DocsEvent
    event: Literal["event"]
    """The event name."""
    id: int | None = None
    """The event ID."""
    retry: int | None = None
    """The retry time in milliseconds."""


class GetEventsResponse(RootModel[list[GetEventsResponse1]]):
    root: Annotated[list[GetEventsResponse1], Field(title="Server Sent Events")]
    """Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification."""
