# generated by datamodel-codegen:
#   filename:  <dict>
#   timestamp: 2026-08-17T11:04:54+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
)


class Metric(StrEnum):
    cpu_percent = "cpu_percent"
    memory_percent = "memory_percent"


class Severity(StrEnum):
    warning = "warning"
    critical = "critical"


class AlertEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[
        str,
        Field(
            description="Human-readable alert description",
            examples=["cpu_percent is critically high at 82.3% (threshold: 80%)"],
        ),
    ]
    metric: Annotated[
        Metric,
        Field(
            description="Name of the metric that triggered the alert",
            examples=["cpu_percent"],
        ),
    ]
    severity: Annotated[Severity, Field(description="Alert severity level", examples=["critical"])]
    threshold: Annotated[float, Field(description="Threshold that was exceeded", examples=[80], ge=0.0)]
    timestamp: Annotated[AwareDatetime, Field(description="Time the alert was raised")]
    value: Annotated[float, Field(description="Current value of the metric", examples=[82.3], ge=0.0)]


class Scheme(StrEnum):
    basic = "basic"
    bearer = "bearer"
    api_key_header = "api-key-header"
    api_key_query = "api-key-query"


class AuthResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/AuthResponseBody.json"],
        ),
    ] = None
    authenticated: Annotated[
        bool,
        Field(
            description="Whether the mock authentication check succeeded",
            examples=[True],
        ),
    ]
    scheme: Annotated[
        Scheme,
        Field(
            description="Authentication scheme that accepted the request",
            examples=["bearer"],
        ),
    ]
    subject: Annotated[
        str | None,
        Field(
            description="Authenticated username, token, or API key",
            examples=["docs-token"],
        ),
    ] = None


class BookSummary(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    modified: Annotated[
        AwareDatetime,
        Field(description="Last modification time used for conditional requests"),
    ]
    url: Annotated[
        str,
        Field(
            description="Relative URL for the book resource",
            examples=["/books/left-hand-of-darkness"],
        ),
    ]
    version: Annotated[
        str,
        Field(
            description="Opaque version token for conditional requests",
            examples=["F5D3XF8rF2F="],
        ),
    ]


class CachedModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/CachedModel.json"],
        ),
    ] = None
    generated: Annotated[AwareDatetime, Field(description="Time when this response was generated")]
    until: Annotated[AwareDatetime, Field(description="When the cache will be invalidated")]


class Type(StrEnum):
    login = "login"
    update = "update"
    logout = "logout"


class DocsUser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(description="User ID", examples=["u_123"], min_length=1)]
    name: Annotated[str, Field(description="Display name", examples=["Alice"], min_length=1)]


class Method(StrEnum):
    get = "GET"
    post = "POST"
    put = "PUT"
    patch = "PATCH"
    delete = "DELETE"
    head = "HEAD"
    options = "OPTIONS"


class EchoModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/EchoModel.json"],
        ),
    ] = None
    body: Annotated[
        Any | None,
        Field(description="Raw request body, either a UTF-8 string or bytes"),
    ] = None
    headers: Annotated[dict[str, str], Field(description="HTTP headers")]
    host: Annotated[
        str | None,
        Field(description="Hostname and optional port", examples=["api.rest.sh"]),
    ] = None
    method: Annotated[Method, Field(description="HTTP method used", examples=["GET"])]
    parsed: Annotated[Any | None, Field(description="Parsed request body")] = None
    path: Annotated[str, Field(description="URL path", examples=["/get"])]
    query: Annotated[dict[str, str] | None, Field(description="URL query parameters")] = None
    url: Annotated[
        AnyUrl,
        Field(description="Full URL", examples=["https://api.rest.sh/get?show_env=1"]),
    ]


class StudyType(StrEnum):
    high_school = "High School"
    bachelor = "Bachelor"
    master = "Master"
    doctorate = "Doctorate"
    certificate = "Certificate"


class Education(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area: Annotated[str | None, Field(description="Field of study", examples=["Computer Science"])] = None
    courses: Annotated[list[str] | None, Field(description="Relevant courses", max_length=20)] = None
    end_date: Annotated[AwareDatetime | None, Field(alias="endDate", description="Education end date")] = None
    gpa: Annotated[
        str | None,
        Field(description="Grade point average or equivalent", examples=["3.8"]),
    ] = None
    institution: Annotated[
        str | None,
        Field(description="School or institution name", examples=["University of Example"]),
    ] = None
    start_date: Annotated[
        AwareDatetime | None,
        Field(alias="startDate", description="Education start date"),
    ] = None
    study_type: Annotated[
        StudyType | None,
        Field(
            alias="studyType",
            description="Type of study or credential",
            examples=["Bachelor"],
        ),
    ] = None


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: Annotated[
        str | None,
        Field(description="Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'"),
    ] = None
    message: Annotated[str | None, Field(description="Error message text")] = None
    value: Annotated[Any | None, Field(description="The value at the given location")] = None


class ErrorModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/ErrorModel.json"],
        ),
    ] = None
    detail: Annotated[
        str | None,
        Field(
            description="A human-readable explanation specific to this occurrence of the problem.",
            examples=["Property foo is required but is missing."],
        ),
    ] = None
    errors: Annotated[
        list[ErrorDetail] | None,
        Field(description="Optional list of individual error details"),
    ] = None
    instance: Annotated[
        AnyUrl | None,
        Field(
            description="A URI reference that identifies the specific occurrence of the problem.",
            examples=["https://example.com/error-log/abc123"],
        ),
    ] = None
    status: Annotated[int | None, Field(description="HTTP status code", examples=[400])] = None
    title: Annotated[
        str | None,
        Field(
            description="A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
            examples=["Bad Request"],
        ),
    ] = None
    type: Annotated[
        AnyUrl | None,
        Field(
            description="A URI reference to human-readable documentation for the error.",
            examples=["https://example.com/errors/example"],
        ),
    ] = "about:blank"


class Format(StrEnum):
    jpeg = "jpeg"
    webp = "webp"
    gif = "gif"
    png = "png"
    heic = "heic"


class ImageItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format: Annotated[
        Format,
        Field(description="Image format returned by the fixture", examples=["jpeg"]),
    ]
    name: Annotated[
        str,
        Field(description="Human-readable image fixture name", examples=["Dragonfly"]),
    ]
    self: Annotated[
        str,
        Field(description="Relative URL for this image fixture", examples=["/image/jpeg"]),
    ]


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/Item.json"],
        ),
    ] = None
    enabled: Annotated[bool, Field(description="Whether the item is enabled", examples=[True])]
    id: Annotated[
        str,
        Field(
            description="Stable item identifier; omit or leave empty when creating an item to have one generated",
            examples=["alpha"],
            max_length=64,
        ),
    ]
    name: Annotated[
        str,
        Field(
            description="Display name",
            examples=["Alpha item"],
            max_length=120,
            min_length=1,
        ),
    ]
    tags: Annotated[
        list[str] | None,
        Field(
            description="Free-form item tags",
            examples=[["docs", "example"]],
            max_length=10,
        ),
    ] = None
    updated: Annotated[AwareDatetime, Field(description="Time when the item was last updated")]


class Op(StrEnum):
    add = "add"
    remove = "remove"
    replace = "replace"
    move = "move"
    copy = "copy"
    test = "test"


class JsonPatchOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_: Annotated[
        str | None,
        Field(alias="from", description="JSON Pointer for the source of a move or copy"),
    ] = None
    op: Annotated[Op, Field(description="Operation name")]
    path: Annotated[
        str,
        Field(description="JSON Pointer to the field being operated on, or the destination of a move/copy operation"),
    ]
    value: Annotated[Any | None, Field(description="The value to set")] = None


class Fluency(StrEnum):
    elementary = "Elementary"
    limited_working = "Limited working"
    professional_working = "Professional working"
    full_professional = "Full professional"
    native_or_bilingual = "Native or bilingual"


class Language(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fluency: Annotated[
        Fluency | None,
        Field(description="Language fluency", examples=["Native or bilingual"]),
    ] = None
    language: Annotated[str | None, Field(description="Language name", examples=["English"])] = None


class Location(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address: Annotated[
        str | None,
        Field(
            description="To add multiple address lines, use \n. For example, 1234 Glücklichkeit Straße\nHinterhaus 5. Etage li."
        ),
    ] = None
    city: Annotated[str | None, Field(description="City or locality", examples=["San Francisco"])] = None
    country_code: Annotated[
        str | None,
        Field(
            alias="countryCode",
            description="Code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN",
            examples=["US"],
            max_length=2,
            min_length=2,
        ),
    ] = None
    postal_code: Annotated[
        str | None,
        Field(alias="postalCode", description="Postal or ZIP code", examples=["94105"]),
    ] = None
    region: Annotated[
        str | None,
        Field(description="The general region where you live. Can be a US state, or a province, for instance."),
    ] = None


class Region(StrEnum):
    us_east_1 = "us-east-1"
    us_west_2 = "us-west-2"
    eu_west_1 = "eu-west-1"
    ap_southeast_1 = "ap-southeast-1"


class MetricEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    active_connections: Annotated[int, Field(description="Number of active HTTP connections", examples=[96], ge=0)]
    cpu_percent: Annotated[
        float,
        Field(description="CPU utilization percentage", examples=[62.4], ge=0.0, le=100.0),
    ]
    memory_percent: Annotated[
        float,
        Field(
            description="Memory utilization percentage",
            examples=[71.2],
            ge=0.0,
            le=100.0,
        ),
    ]
    region: Annotated[
        Region,
        Field(description="Data center region reporting metrics", examples=["us-west-2"]),
    ]
    requests_per_second: Annotated[
        float,
        Field(description="Inbound request rate", examples=[421.5], ge=0.0, le=2000.0),
    ]
    timestamp: Annotated[AwareDatetime, Field(description="Time the metrics were sampled")]


class Profile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    network: Annotated[
        str | None,
        Field(
            description="Profile network or service name",
            examples=["Twitter"],
            min_length=1,
        ),
    ] = None
    url: Annotated[AnyUrl | None, Field(examples=["http://twitter.example.com/neutralthoughts"])] = None
    username: Annotated[
        str | None,
        Field(
            description="Username on the profile network",
            examples=["neutralthoughts"],
            min_length=1,
        ),
    ] = None


class Rating(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: Annotated[AwareDatetime, Field(description="Time when the rating was recorded")]
    rating: Annotated[
        float,
        Field(
            description="Rating value on a 0 to 5 scale",
            examples=[4.6],
            ge=0.0,
            le=5.0,
            multiple_of=0.1,
        ),
    ]


class Level(StrEnum):
    beginner = "Beginner"
    intermediate = "Intermediate"
    advanced = "Advanced"
    expert = "Expert"


class Skill(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    keywords: Annotated[
        list[str] | None,
        Field(
            description="Specific technologies or practices",
            max_length=20,
            min_length=1,
        ),
    ] = None
    level: Annotated[Level | None, Field(description="Proficiency level", examples=["Advanced"])] = None
    name: Annotated[
        str | None,
        Field(description="Skill category name", examples=["Web Development"]),
    ] = None


class SubObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    binary: Annotated[
        str,
        Field(
            description="Small binary payload encoded as base64 in JSON",
            json_schema_extra={"contentEncoding": "base64"},
            min_length=1,
        ),
    ]
    binary_long: Annotated[
        str,
        Field(
            description="Longer binary payload encoded as base64 in JSON",
            json_schema_extra={"contentEncoding": "base64"},
            min_length=1,
        ),
    ]
    date: Annotated[
        AwareDatetime,
        Field(description="Calendar date represented as an RFC 3339 timestamp"),
    ]
    date_time: Annotated[AwareDatetime, Field(description="Full timestamp with timezone")]
    url: Annotated[AnyUrl, Field(description="Absolute URL example", examples=["https://rest.sh/"])]


class TokenType(StrEnum):
    bearer = "Bearer"


class TokenResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/TokenResponseBody.json"],
        ),
    ] = None
    token: Annotated[
        str,
        Field(
            description="Mock bearer token for documentation examples",
            examples=["docs-token-alice"],
        ),
    ]
    token_type: Annotated[TokenType, Field(description="Token type", examples=["Bearer"])]
    user: Annotated[str, Field(description="Username from the submitted form", examples=["alice"])]


class TypesModelNullableStruct(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class UploadFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content_type: Annotated[
        str | None,
        Field(description="Detected file content type", examples=["image/png"]),
    ] = None
    field: Annotated[str, Field(description="Multipart field name", examples=["avatar"])]
    filename: Annotated[str, Field(description="Uploaded filename", examples=["avatar.png"])]
    size: Annotated[int, Field(description="File size in bytes", examples=[2048], ge=0)]


class UploadResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/UploadResponseBody.json"],
        ),
    ] = None
    fields: Annotated[
        dict[str, list[str] | None],
        Field(description="Non-file multipart fields grouped by field name"),
    ]
    files: Annotated[list[UploadFile] | None, Field(description="Uploaded file metadata")]


class Volunteer(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    end_date: Annotated[
        AwareDatetime | None,
        Field(alias="endDate", description="Volunteer role end date"),
    ] = None
    highlights: Annotated[
        list[str] | None,
        Field(description="Notable volunteer accomplishments", max_length=10),
    ] = None
    organization: Annotated[
        str | None,
        Field(description="Volunteer organization name", examples=["Code for America"]),
    ] = None
    position: Annotated[str | None, Field(description="Volunteer role", examples=["Mentor"])] = None
    start_date: Annotated[
        AwareDatetime | None,
        Field(alias="startDate", description="Volunteer role start date"),
    ] = None
    summary: Annotated[str | None, Field(description="Overview of the volunteer work")] = None
    url: Annotated[AnyUrl | None, Field(examples=["https://www.codeforamerica.org"])] = None


class Work(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Annotated[str | None, Field(examples=["Social Media Company"])] = None
    end_date: Annotated[
        AwareDatetime | None,
        Field(alias="endDate", description="Role end date, omitted for current roles"),
    ] = None
    highlights: Annotated[
        list[str] | None,
        Field(description="Specify multiple accomplishments", max_length=10),
    ] = None
    location: Annotated[str | None, Field(examples=["Menlo Park, CA"])] = None
    name: Annotated[
        str,
        Field(
            description="Employer or organization name",
            examples=["Facebook"],
            min_length=1,
        ),
    ]
    position: Annotated[
        str,
        Field(
            description="Job title or role",
            examples=["Software Engineer"],
            min_length=1,
        ),
    ]
    start_date: Annotated[AwareDatetime | None, Field(alias="startDate", description="Role start date")] = None
    summary: Annotated[
        str | None,
        Field(description="Give an overview of your responsibilities at the company"),
    ] = None
    url: Annotated[AnyUrl | None, Field(examples=["https://facebook.com"])] = None


class GetBase64DecodeResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class GetBase64EncodeResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class ListBooksResponse(RootModel[list[BookSummary] | None]):
    root: list[BookSummary] | None


class PatchBookRequest(RootModel[list[JsonPatchOp] | None]):
    root: list[JsonPatchOp] | None


class PatchBookRequest1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/Book.json"],
        ),
    ] = None
    author: Annotated[
        str | None,
        Field(
            description="Primary author",
            examples=["Ursula K. Le Guin"],
            max_length=120,
            min_length=1,
        ),
    ] = None
    published: Annotated[AwareDatetime | None, Field(description="Publication date")] = None
    rating_average: Annotated[
        float | None,
        Field(
            description="Average rating on a 0 to 5 scale",
            examples=[4.4],
            ge=0.0,
            le=5.0,
            multiple_of=0.1,
        ),
    ] = None
    ratings: Annotated[int | None, Field(description="Total number of ratings", examples=[1287], ge=0)] = None
    recent_ratings: Annotated[list[Any] | None, Field(description="Most recent rating samples", max_length=10)] = None
    title: Annotated[
        str | None,
        Field(
            description="Book title",
            examples=["The Left Hand of Darkness"],
            max_length=200,
            min_length=1,
        ),
    ] = None


class GetCookiesResponse(RootModel[dict[str, dict[str, str]]]):
    root: dict[str, dict[str, str]]


class GetCookiesDeleteResponse(RootModel[dict[str, list[str] | None]]):
    root: dict[str, list[str] | None]


class GetCookiesSetResponse(RootModel[dict[str, dict[str, str]]]):
    root: dict[str, dict[str, str]]


class GetFlakyResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetHeadersResponse(RootModel[dict[str, dict[str, str]]]):
    root: dict[str, dict[str, str]]


class ListImagesResponse(RootModel[list[ImageItem] | None]):
    root: list[ImageItem] | None


class GetIpResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class ListItemsResponse(RootModel[list[Item] | None]):
    root: list[Item] | None


class PatchItemRequest(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetProblemResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetResponseHeadersResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class GetSlowResponse(RootModel[dict[str, Any]]):
    root: dict[str, Any]


class GetSseMetricsResponse1(BaseModel):
    data: AlertEvent
    event: Annotated[Literal["alert"], Field(description="The event name.")]
    id: Annotated[int | None, Field(description="The event ID.")] = None
    retry: Annotated[int | None, Field(description="The retry time in milliseconds.")] = None


class GetSseMetricsResponse2(BaseModel):
    data: MetricEvent
    event: Annotated[Literal["metrics"], Field(description="The event name.")]
    id: Annotated[int | None, Field(description="The event ID.")] = None
    retry: Annotated[int | None, Field(description="The retry time in milliseconds.")] = None


class GetSseMetricsResponse(RootModel[list[GetSseMetricsResponse1 | GetSseMetricsResponse2]]):
    root: Annotated[
        list[GetSseMetricsResponse1 | GetSseMetricsResponse2],
        Field(
            description="Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification.",
            title="Server Sent Events",
        ),
    ]


class GetUserAgentResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class GetUuidResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class Basics(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    email: Annotated[
        EmailStr | None,
        Field(description="Contact email address", examples=["thomas@gmail.com"]),
    ] = None
    image: Annotated[
        AnyUrl | None,
        Field(
            description="URL (as per RFC 3986) to an image in JPEG or PNG format",
            examples=["https://example.com/avatar.jpg"],
        ),
    ] = None
    label: Annotated[
        str | None,
        Field(
            description="Short professional headline",
            examples=["Web Developer"],
            min_length=1,
        ),
    ] = None
    location: Annotated[Location | None, Field(description="Primary location")] = None
    name: Annotated[
        str,
        Field(description="Full display name", examples=["Thomas Davis"], min_length=1),
    ]
    phone: Annotated[
        str | None,
        Field(description="Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923"),
    ] = None
    profiles: Annotated[
        list[Profile] | None,
        Field(description="Online social or professional profiles", max_length=10),
    ] = None
    summary: Annotated[
        str | None,
        Field(description="Write a short 2-3 sentence biography about yourself"),
    ] = None
    updated: Annotated[AwareDatetime, Field(description="Time when the resume data was last updated")]
    url: Annotated[
        AnyUrl | None,
        Field(description="URL (as per RFC 3986) to your website, e.g. personal homepage"),
    ] = None
    verified: Annotated[
        bool,
        Field(
            description="Whether this example profile has been verified",
            examples=[True],
        ),
    ]


class Book(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/Book.json"],
        ),
    ] = None
    author: Annotated[
        str | None,
        Field(
            description="Primary author",
            examples=["Ursula K. Le Guin"],
            max_length=120,
            min_length=1,
        ),
    ] = None
    published: Annotated[AwareDatetime | None, Field(description="Publication date")] = None
    rating_average: Annotated[
        float | None,
        Field(
            description="Average rating on a 0 to 5 scale",
            examples=[4.4],
            ge=0.0,
            le=5.0,
            multiple_of=0.1,
        ),
    ] = None
    ratings: Annotated[int | None, Field(description="Total number of ratings", examples=[1287], ge=0)] = None
    recent_ratings: Annotated[
        list[Rating] | None,
        Field(description="Most recent rating samples", max_length=10),
    ] = None
    title: Annotated[
        str,
        Field(
            description="Book title",
            examples=["The Left Hand of Darkness"],
            max_length=200,
            min_length=1,
        ),
    ]


class DocsEvent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: Annotated[
        str,
        Field(description="Human-readable message", examples=["login event for Alice"]),
    ]
    timestamp: Annotated[AwareDatetime, Field(description="Event timestamp")]
    type: Annotated[Type, Field(description="Event type", examples=["login"])]
    user: Annotated[DocsUser, Field(description="User associated with the event")]


class Resume(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/Resume.json"],
        ),
    ] = None
    basics: Annotated[Basics, Field(description="Core profile and contact information")]
    education: Annotated[list[Education] | None, Field(description="Education history")] = None
    languages: Annotated[list[Language] | None, Field(description="Spoken languages")] = None
    skills: Annotated[list[Skill] | None, Field(description="Skills and keywords")] = None
    volunteer: Annotated[list[Volunteer] | None, Field(description="Volunteer experience")] = None
    work: Annotated[list[Work] | None, Field(description="Professional work history", min_length=1)]


class TypesModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_schema: Annotated[
        AnyUrl | None,
        Field(
            alias="$schema",
            description="A URL to the JSON Schema for this object.",
            examples=["https://api.rest.sh/schemas/TypesModel.json"],
        ),
    ] = None
    boolean: Annotated[bool, Field(description="Boolean example value", examples=[True])]
    integer: Annotated[
        int,
        Field(
            description="Integer example with validation bounds",
            examples=[42],
            ge=0,
            le=100,
        ),
    ]
    nullable: Annotated[
        TypesModelNullableStruct,
        Field(description="Nullable object field; this response intentionally returns null"),
    ]
    number: Annotated[
        float,
        Field(
            description="Floating point example with precision constraints",
            examples=[123.45],
            ge=0.0,
            le=1000.0,
            multiple_of=0.01,
        ),
    ]
    object: Annotated[
        SubObject,
        Field(description="Nested object showing binary, date-time, and URI fields"),
    ]
    string: Annotated[
        str,
        Field(
            description="Plain UTF-8 string example",
            examples=["Hello, world!"],
            max_length=120,
            min_length=1,
        ),
    ]
    tags: Annotated[
        list[str] | None,
        Field(
            description="Short list of descriptive tags",
            examples=[["example", "short"]],
            max_length=5,
            min_length=1,
        ),
    ]


class GetEventsResponse1(BaseModel):
    data: DocsEvent
    event: Annotated[Literal["event"], Field(description="The event name.")]
    id: Annotated[int | None, Field(description="The event ID.")] = None
    retry: Annotated[int | None, Field(description="The retry time in milliseconds.")] = None


class GetEventsResponse(RootModel[list[GetEventsResponse1]]):
    root: Annotated[
        list[GetEventsResponse1],
        Field(
            description="Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification.",
            title="Server Sent Events",
        ),
    ]
