# generated by datamodel-codegen:
#   filename:  <dict>
#   timestamp: 2026-08-20T01:47:09+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Status(StrEnum):
    placed = "placed"
    approved = "approved"
    delivered = "delivered"


class Order(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "order"}},
    )
    id: Annotated[int | None, Field(examples=[10])] = None
    """Example: 10"""
    pet_id: Annotated[int | None, Field(alias="petId", examples=[198772])] = None
    """Example: 198772"""
    quantity: Annotated[int | None, Field(examples=[7])] = None
    """Example: 7"""
    ship_date: Annotated[AwareDatetime | None, Field(alias="shipDate")] = None
    status: Annotated[Status | None, Field(examples=["approved"])] = None
    """
    Order Status

    Example: 'approved'
    """
    complete: bool | None = None


class Category(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "category"}},
    )
    id: Annotated[int | None, Field(examples=[1])] = None
    """Example: 1"""
    name: Annotated[str | None, Field(examples=["Dogs"])] = None
    """Example: 'Dogs'"""


class User(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "user"}},
    )
    id: Annotated[int | None, Field(examples=[10])] = None
    """Example: 10"""
    username: Annotated[str | None, Field(examples=["theUser"])] = None
    """Example: 'theUser'"""
    first_name: Annotated[str | None, Field(alias="firstName", examples=["John"])] = None
    """Example: 'John'"""
    last_name: Annotated[str | None, Field(alias="lastName", examples=["James"])] = None
    """Example: 'James'"""
    email: Annotated[str | None, Field(examples=["john@email.com"])] = None
    """Example: 'john@email.com'"""
    password: Annotated[str | None, Field(examples=["12345"])] = None
    """Example: '12345'"""
    phone: Annotated[str | None, Field(examples=["12345"])] = None
    """Example: '12345'"""
    user_status: Annotated[int | None, Field(alias="userStatus", examples=[1])] = None
    """
    User Status

    Example: 1
    """


class Tag(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "tag"}},
    )
    id: int | None = None
    name: str | None = None


class Status1(StrEnum):
    available = "available"
    pending = "pending"
    sold = "sold"


class Pet(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "pet"}},
    )
    id: Annotated[int | None, Field(examples=[10])] = None
    """Example: 10"""
    name: Annotated[str, Field(examples=["doggie"])]
    """Example: 'doggie'"""
    category: Category | None = None
    photo_urls: Annotated[
        list[str],
        Field(alias="photoUrls", json_schema_extra={"xml": {"wrapped": True}}),
    ]
    tags: Annotated[list[Tag] | None, Field(json_schema_extra={"xml": {"wrapped": True}})] = None
    status: Status1 | None = None
    """pet status in the store"""


class ApiResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"xml": {"name": "##default"}},
    )
    code: int | None = None
    type: str | None = None
    message: str | None = None


class FindPetsByStatusResponse(RootModel[list[Pet]]):
    root: list[Pet]


class FindPetsByTagsResponse(RootModel[list[Pet]]):
    root: list[Pet]


class GetInventoryResponse(RootModel[dict[str, int]]):
    root: dict[str, int]


class CreateUsersWithListInputRequest(RootModel[list[User]]):
    root: list[User]
